import os
import torch
from torchvision.utils import save_image

from dcgan import Generator

project_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
training_models_dir = os.path.join(project_dir, "training_models")
generated_images_dir = os.path.join(project_dir, "generated_images")

# Note: The parameters for the generator should match those used during training. Adjust them as necessary.
params = {
    'nc': 1,
    'nz': 100,
    'ngf': 64,
}

# Check if GPU is available, else use CPU
if torch.cuda.is_available():
    device = torch.device("cuda")
elif torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")

print("Using device:", device)

model = Generator(params).to(device)
# Note: You can change the model here if you want to load a different trained model. 
model.load_state_dict(torch.load(os.path.join(training_models_dir, "generator_trained.pth"), map_location=device))
model.eval()

os.makedirs(generated_images_dir, exist_ok=True)
# Note: You can change the number of images generated by modifying the first argument of torch.randn below.
noise = torch.randn(20, 100, 1, 1, device=device)

with torch.no_grad():
    images = model(noise)

# Save the generated images to the "GENERATED_images" directory
for index, image in enumerate(images, start=1):
    save_image(image, os.path.join(generated_images_dir, f"image_{index:02d}.png"), normalize=True, value_range=(-1, 1))

print(f"Saved 20 images to {generated_images_dir}/")
